[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cognitive-core-engine"
version = "0.1.0"
description = "Cognitive Core Engine with FastAPI API, math services, and plugin registry."
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [{name="Yaroslav"}]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Framework :: FastAPI",
]
dependencies = [
  "fastapi>=0.111.0",
  "uvicorn>=0.29.0",
  "pydantic>=2.7.0",
  "pydantic-settings>=2.2.0",
  "anyio>=4.4.0",
  "fastapi>=0.112",
  "uvicorn[standard]>=0.30",
  "pydantic>=2.7",
  "pydantic-settings>=2.3",
  "typer>=0.12",
  "anyio>=4.4",
  "requests>=2.32",
  "redis>=5.0",
  "SQLAlchemy>=2.0",
  "alembic>=1.13",
  "psycopg2-binary>=2.9",
  "prometheus-client>=0.20",
  "structlog>=24.1",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.0.0",
  "httpx>=0.27.0",
  "pytest-benchmark>=4.0.0",
  "ruff>=0.6.8",
  "black>=24.8.0",
  "isort>=5.13.2",
  "pre-commit>=3.7.0"
]

[project.scripts]
cogctl = "cognitive_core.cli:app"

[tool.pytest.ini_options]
addopts = "-q --disable-warnings --maxfail=1 --cov=src/cognitive_core --cov-report=term-missing"
testpaths = ["tests"]

[tool.isort]
profile = "black"
known_first_party = ["tools", "cognitive_core", "api"]

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
