[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cognitive-core-engine"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = [
  "pydantic>=2.7",
  "typing-extensions>=4.8",
]

[project.optional-dependencies]
api = [
  "fastapi>=0.111",
  "uvicorn>=0.29",
  "httpx>=0.25",
]
test = [
  "pytest>=7.4",
  "pytest-cov>=4.1",
  "httpx>=0.25",
  "hypothesis>=6.99",
  "pyyaml>=6.0.1",
]

dev = [
  "ruff>=0.5.0",
  "black>=24.4",
  "isort>=5.13",
  "mypy>=1.8",
  "types-requests",
]
security = [
  "bandit>=1.7.5",
  "pip-audit>=2.7",
]
docs = [
  "mkdocs>=1.5",
  "mkdocs-material>=9.5",
]
[tool.black]
line-length = 100
target-version = ["py310","py311","py312"]

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true
known_first_party = ["cognitive_core"]

[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E","F","I"]
ignore = ["E203","E266","E501","F401","F841"]  # тимчасово; приберемо після прибирання імпортів
src = ["src","cognitive_core","."]

[tool.pytest.ini_options]
addopts = "-q -ra --strict-markers --disable-warnings --maxfail=1"
testpaths = ["tests"]
markers = [
    "integration: tests hitting real services",
    "slow: long-running tests",
    "flaky: flaky tests to be stabilized",
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
]
