name: Bug Report
description: File a bug report
labels: ["type/ci"]
body:
  - type: textarea
    id: bug
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: Steps to reproduce
    validations:
      required: true
