name: CI

on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "setup"
  lint:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: write   # потрібно, щоб автокомітнути зміни форматування
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -e ".[dev]" || pip install ruff black isort
      - name: Auto-format (ruff+black+isort)
        run: |
          ruff check . --fix || true
          black . || true
          isort . || true
      - name: Auto-commit formatting
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style(fmt): auto-format via CI (ruff/black/isort)"
          commit_user_name: bot-ci
          commit_user_email: bot@example.com
          skip_dirty_check: false
      - name: Ruff (verify)
        run: ruff check .
      - name: Black (verify)
        run: black --check .
      - name: isort (verify)
        run: isort --check-only .

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -e ".[api,test,dev,security,docs]" || pip install -e .
      - name: Mypy
        run: mypy .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -e ".[api,test,dev,security,docs]" || pip install -e .
      - name: Pytest
        run: pytest -q

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -e ".[api,test,dev,security,docs]" || pip install -e .
      - name: Bandit
        run: bandit -r .
      - name: Pip Audit
        run: pip-audit --skip-deps --strict

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -e ".[api,test,dev,security,docs]" || pip install -e .
      - name: Build docs
        run: mkdocs build --strict
