name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -e ".[api,test,dev,security,docs]" || pip install -e .
      - name: Auto-format (ruff+black+isort)
        run: |
          ruff check . --fix
          black .
          isort .
      - name: Ruff
        run: ruff check .
      - name: Black
        run: black --check .
      - name: Isort
        run: isort --check-only .

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -e ".[api,test,dev,security,docs]" || pip install -e .
      - name: Mypy
        run: mypy .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -e ".[api,test,dev,security,docs]" || pip install -e .
      - name: Pytest
        run: pytest -q

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -e ".[api,test,dev,security,docs]" || pip install -e .
      - name: Bandit
        run: bandit -r .
      - name: Pip Audit
        run: pip-audit --skip-deps --strict

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -e ".[api,test,dev,security,docs]" || pip install -e .
      - name: Build docs
        run: mkdocs build --strict
