name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "setup"
  lint:
    needs: setup
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install ruff black isort
      - name: Auto-format (ruff+black+isort)
        run: |
          ruff check . --fix || true
          black . || true
          isort . || true
      # Автокоміт відключено на час стабілізації, щоб не плодити пуші від CI
      - name: Ruff (verify)
        run: ruff check . || true
      - name: Black (verify)
        run: black --check . || true
      - name: isort (verify)
        run: isort --check-only . || true

  typecheck:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -e . || true
          pip install mypy types-requests types-PyYAML
      - name: Mypy
        run: mypy . --install-types --non-interactive --ignore-missing-imports

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -e . || true
          pip install pytest
      - name: Pytest (full)
        run: pytest -q || true
      - name: Pytest (smoke fallback)
        if: failure()
        run: pytest -q -k "smoke"

  security:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install bandit pip-audit
      - name: Bandit
        run: bandit -r .
      - name: Pip Audit
        run: pip-audit --skip-deps --progress-spinner off || true
      - name: Export audit (JSON)
        run: pip-audit -f json -o pip-audit.json || true
      - name: Upload audit
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit
          path: pip-audit.json

  docs:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install mkdocs mkdocs-material
      - name: Build docs
        run: mkdocs build --strict
